services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: TecChallenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  api-tec-challenge: 
    container_name: api-tec-challenge
    build: .
    environment:
        ASPNETCORE_ENVIRONMENT: Local 
        DOTNET_RUNNING_IN_CONTAINER: "true"
        ASPNETCORE_URLS: "http://+:5001" 
    ports:
      - "5001:5001"
    restart: on-failure
    depends_on:
      postgres-db:
        condition: service_healthy
      
volumes:
  postgres_data:
