apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tec-challenge-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: tec-challenge-service
            port:
              number: 8081
        path: /()(.*)
        pathType: Prefix